services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11   # <- specify Python 3.11 here
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
        value: "<YOUR_BOT_TOKEN_HERE>"
